# permissions for end users to edit masters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: master-editor-role
rules:
- apiGroups:
  - objectstore.seaweedfs.com
  resources:
  - masters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - objectstore.seaweedfs.com
  resources:
  - masters/status
  verbs:
  - get
