apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: seaweedfsclusters.cluster.seaweedfs.com
spec:
  group: cluster.seaweedfs.com
  names:
    kind: SeaweedfsCluster
    listKind: SeaweedfsClusterList
    plural: seaweedfsclusters
    singular: seaweedfscluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SeaweedfsCluster is the Schema for the seaweedfsclusters API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SeaweedfsClusterSpec defines the desired state of SeaweedfsCluster
          properties:
            filer:
              description: SeaweedfsFilerSpec defines the desired state of filer server
                in cluster
              properties:
                dir_list_limit:
                  description: DirListLimit limit sub dir listing size, default 100000
                  format: int32
                  type: integer
                disable_dir_listing:
                  description: DisableDirListing turn off directory listing
                  type: boolean
                max_mb:
                  description: MaxMB split files larger than the limit, default 32
                  format: int32
                  type: integer
                port:
                  description: Port filer server http listen port
                  format: int32
                  type: integer
                replicas:
                  description: Replicas a size of filer replications
                  format: int32
                  type: integer
              type: object
            master:
              description: SeaweedfsMasterSpec defines the desired state of master
                server in cluster
              properties:
                default_replication:
                  description: DefaultReplication set the data replication policy
                    in volumes. default "000"
                  type: string
                disable_http:
                  description: DisableHTTP if disable http proto, only gRPC operations
                    are allowed. GRPC port is http port + 10000
                  type: boolean
                port:
                  description: Port set master server http api service port. default
                    is 9333 Master servers also use it identify each other.
                  format: int32
                  type: integer
                replication_size:
                  description: Replicas a size of a raft cluster. The master servers
                    are coordinated by Raft protocol, to elect a leader.
                  format: int32
                  type: integer
              type: object
            version:
              type: string
            volumes:
              items:
                description: SeaweedfsVolumeSpec defines the desired state of volume
                  servers in cluster
                properties:
                  compaction_mbps:
                    description: CompactionMbps limit background compaction or copying
                      speed in mega bytes per second
                    format: int32
                    type: integer
                  data_center:
                    description: DataCenter current volume server's data center name
                    type: string
                  max:
                    description: Max set the maximum numbers of volumes management
                      by this server. Each volume is a 30G size file in under layer
                      filesystem. Default is 7
                    format: int32
                    type: integer
                  port:
                    description: Port volume server api http listen port
                    format: int32
                    type: integer
                  rack:
                    description: Rack current volume server's rack name
                    type: string
                type: object
              type: array
          type: object
        status:
          description: SeaweedfsClusterStatus defines the observed state of SeaweedfsCluster
          type: object
      type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
