apiVersion: apps/v1
kind: Deployment
metadata:
  name: seaweedfs-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: seaweedfs-operator
  template:
    metadata:
      labels:
        name: seaweedfs-operator
    spec:
      serviceAccountName: seaweedfs-operator
      containers:
        - name: seaweedfs-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
            - seaweedfs-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "seaweedfs-operator"
