## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry
##
# global:
#   imageRegistry: myRegistryName

## String to partially override common.names.fullname template (will maintain the release name)
##
# nameOverride:

## String to fully override common.names.fullname template
##
# fullnameOverride:

## Annotations for all the deployed objects
##
# commonAnnotations: {}

## Labels for all the deployed objects
##
# commonLabels: {}

## Configure rbac parameters
##
rbac:
  serviceAccount:
    name: default
    namespace: operators

image:
  registry: chrislusf
  repository: seaweedfs-operator
  ## tag value taken from appVersion of Chart.yaml
  ## tag: 3.0.0.
  ## Specify a imagePullPolicy
  ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  ##
  pullPolicy: Always

  ## Specify credentials to authorize in docker registry or set existing secrets in pullSecrets
  credentials:
    registry: private-registry
    username: username
    password: password

  ## Optionally specify imagePullSecret.
  ## Secrets must be manually created in the namespace.
  ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
  ##
  # pullSecrets: myRegistryKeySecretName

## Set number of replicas
##
replicaCount: 1

## Configure container port
##
port:
  name: http
  number: 8080

## Configure Service
##
service:
  portName: http
  port: 8080

## Enable or disable Grafana Dashboard configmap
##
grafanaDashboard:
  enabled: true

## Enable or disable ServiceMonitor
##
serviceMonitor:
  enabled: true
  ## Specify the namespace in which the serviceMonitor resource will be created
  ##
  # namespace: ""
  ## Specify the interval at which metrics should be scraped
  ##
  interval: 10s
  ## Specify the timeout after which the scrape is ended
  ##
  scrapeTimeout: 10s
  ## Specify Metric Relabellings to add to the scrape endpoint
  ##
  ## Specify honorLabels parameter to add the scrape endpoint
  ##
  honorLabels: true
  ## Specify the release for ServiceMonitor. Sometimes it should be custom for prometheus operator to work
  ##
  # release: ""
  ## Used to pass Labels that are used by the Prometheus installed in your cluster to select Service Monitors to work with
  ## ref: https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#prometheusspec
  ##
  additionalLabels: {}

## Enable or disable webhooks
##
webhook:
  enabled: true

## seaweedfs-operators containers' resource requests and limits.
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 50Mi