apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed1
spec:
  # Add fields here
  image: chrislusf/seaweedfs:2.08
  volumeServerDiskCount: 1
  master:
    replicas: 3
  volume:
    replicas: 1
    requests:
      storage: 2Gi
  filer:
    replicas: 2

