apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed1
spec:
  # Add fields here
  image: chrislusf/seaweedfs:2.08
  volumeServerDiskCount: 1
  master:
    replicas: 3
    volumeSizeLimitMB: 1024
  volume:
    replicas: 1
    requests:
      storage: 2Gi
  filer:
    replicas: 2
    config: |
      [leveldb2]
      # local on disk, mostly for simple single-machine setup, fairly scalable
      # faster than previous leveldb, recommended.
      enabled = true
      dir = "."                    # directory to store level db files

